[build]
  command = "npm install"
  publish = "/opt/build/repo/public"
  functionsDirectory = "/opt/build/repo/netlify/functions"

[[redirects]]
  from = "/callback"
  to = "/"
  status = 200
